import { DateTime } from 'luxon';
import type { SessionDefinition, SessionOccurrence, SessionStatus } from './types.js';

/**
 * Session engine.
 *
 * Occurrences are generated by walking local calendar days in each session's
 * own timezone, so DST transitions shift the UTC boundary automatically
 * instead of drifting the session an hour off its local open.
 */

function occurrenceForLocalDate(
  definition: SessionDefinition,
  localDate: DateTime,
): SessionOccurrence | null {
  if (!definition.days.includes(localDate.weekday)) return null;

  const start = localDate.startOf('day').plus({ minutes: definition.startMinutes });
  const wrapsMidnight = definition.endMinutes <= definition.startMinutes;
  const end = localDate
    .startOf('day')
    .plus({ minutes: definition.endMinutes + (wrapsMidnight ? 1440 : 0) });

  if (!start.isValid || !end.isValid) return null;

  return {
    definition,
    start: Math.floor(start.toSeconds()),
    end: Math.floor(end.toSeconds()),
  };
}

/**
 * All occurrences of `definition` overlapping [from, to] (UTC epoch seconds).
 * The window is padded by a day on each side so sessions that wrap midnight
 * or start in a different timezone's "yesterday" are still captured.
 */
export function sessionOccurrences(
  definition: SessionDefinition,
  from: number,
  to: number,
): SessionOccurrence[] {
  if (!definition.enabled) return [];

  const first = DateTime.fromSeconds(from, { zone: 'utc' })
    .setZone(definition.timezone)
    .startOf('day')
    .minus({ days: 1 });
  const last = DateTime.fromSeconds(to, { zone: 'utc' })
    .setZone(definition.timezone)
    .startOf('day')
    .plus({ days: 1 });

  const out: SessionOccurrence[] = [];
  for (let day = first; day <= last; day = day.plus({ days: 1 })) {
    const occurrence = occurrenceForLocalDate(definition, day);
    if (occurrence && occurrence.end >= from && occurrence.start <= to) {
      out.push(occurrence);
    }
  }
  return out.sort((a, b) => a.start - b.start);
}

export function allSessionOccurrences(
  definitions: SessionDefinition[],
  from: number,
  to: number,
): SessionOccurrence[] {
  return definitions
    .flatMap((definition) => sessionOccurrences(definition, from, to))
    .sort((a, b) => a.start - b.start);
}

/** Sessions containing `at`. A session is inclusive of its open, exclusive of its close. */
export function activeSessions(
  definitions: SessionDefinition[],
  at: number,
): SessionOccurrence[] {
  return allSessionOccurrences(definitions, at - 86400, at + 86400).filter(
    (occurrence) => occurrence.start <= at && at < occurrence.end,
  );
}

/** Full status snapshot used by the dashboard header. */
export function sessionStatus(
  definitions: SessionDefinition[],
  at: number,
  horizonDays = 5,
): SessionStatus {
  const horizon = at + horizonDays * 86400;
  const occurrences = allSessionOccurrences(definitions, at - 86400, horizon);

  const active = occurrences.filter((o) => o.start <= at && at < o.end);
  const upcoming = occurrences.filter((o) => o.start > at);
  const next = upcoming.length > 0 ? upcoming[0]! : null;

  const soonestClose = active.reduce<number | null>(
    (acc, o) => (acc === null || o.end < acc ? o.end : acc),
    null,
  );

  return {
    active,
    next,
    secondsToNextOpen: next ? next.start - at : null,
    secondsToActiveClose: soonestClose === null ? null : soonestClose - at,
    executionWindow: active.some((o) => o.definition.tradingPermitted),
    activeNames: active.map((o) => o.definition.name),
  };
}

/**
 * The session an instant belongs to, for journalling and statistics.
 * Overlap windows win over their parent sessions; otherwise the most recently
 * opened session is used.
 */
export function sessionLabelAt(
  definitions: SessionDefinition[],
  at: number,
): string {
  const active = activeSessions(definitions, at);
  if (active.length === 0) return 'Outside session';
  const overlap = active.find((o) => o.definition.kind === 'overlap');
  if (overlap) return overlap.definition.name;
  return active.sort((a, b) => b.start - a.start)[0]!.definition.name;
}

export type MarketStatus = 'open' | 'closed' | 'weekend';

/**
 * Spot gold trades roughly Sunday 22:00 UTC to Friday 22:00 UTC, with a daily
 * broker rollover break. Brokers differ, so the window is configurable.
 */
export interface MarketHoursConfig {
  openWeekday: number;
  openMinutesUtc: number;
  closeWeekday: number;
  closeMinutesUtc: number;
  /** Daily rollover break, in UTC minutes past midnight. */
  dailyBreakStartUtc: number | null;
  dailyBreakMinutes: number;
}

export const DEFAULT_MARKET_HOURS: MarketHoursConfig = {
  openWeekday: 7, // Sunday
  openMinutesUtc: 22 * 60,
  closeWeekday: 5, // Friday
  closeMinutesUtc: 22 * 60,
  dailyBreakStartUtc: 21 * 60,
  dailyBreakMinutes: 60,
};

export function marketStatus(at: number, config = DEFAULT_MARKET_HOURS): MarketStatus {
  const utc = DateTime.fromSeconds(at, { zone: 'utc' });
  const weekday = utc.weekday;
  const minutes = utc.hour * 60 + utc.minute;

  if (weekday === 6) return 'weekend';
  if (weekday === 7 && minutes < config.openMinutesUtc) return 'weekend';
  if (weekday === config.closeWeekday && minutes >= config.closeMinutesUtc) return 'weekend';

  if (config.dailyBreakStartUtc !== null) {
    const breakEnd = config.dailyBreakStartUtc + config.dailyBreakMinutes;
    if (minutes >= config.dailyBreakStartUtc && minutes < breakEnd) return 'closed';
  }
  return 'open';
}
